### ISSUE TITLE
Gif saving optimization

### ISSUE THREAD

**Issue by Gabbo62** [Emanueleff/KRusty-Grab-125#2]
The gif image saving takes around 2.5 seconds in release build.

If considered a problem another library can be used to optimize the time required for the image to be saved.

**[File to be modified](https://github.com/Emanueleff/KRusty-Grab-125/blob/Gabb1/krusty_grab/src/screenshot/screen_capture.rs)**
`save_file` function
Code that create the issue
- `im.save_with_format(save_path, format)
        .expect("Unable to save the image");`

**Comment by Emanueleff** [comment]
solved using raw GifEncoder function to encode only 1 frame + speed specification of the encoder 
(quality loss? doesn't seem - yet to be fully checked)
